# 13 — Select Columns and Rows

## Goal
Select useful columns and rows with simple Pandas commands.

In [1]:
from pathlib import Path

import numpy as np
import pandas as pd

DATA_DIR = Path("../data")
RAW_PATH = DATA_DIR / "raw" / "motionsense_raw.csv"
PROCESSED_DIR = DATA_DIR / "processed"

pd.set_option("display.max_columns", 20)
pd.set_option("display.width", 120)

## Why selection matters
Real datasets often contain more columns than we need.

Selection lets us focus on the useful parts of the data.

In [2]:
df = pd.read_csv(RAW_PATH)

# Select one column.
# A single column in Pandas is called a Series.
activities = df["activity"]
activities.head()

0    Walking
1    Walking
2    Walking
3    Walking
4    Walking
Name: activity, dtype: str

In [3]:
# Select multiple columns by passing a list of column names.
# This creates a smaller DataFrame.
sensor_preview = df[["subject", "activity", "acc_x", "acc_y", "acc_z"]]
sensor_preview.head()

   subject activity     acc_x     acc_y     acc_z
0        3  Walking -0.190664  0.687583  1.129328
1       24  Walking  0.010593  0.542629  0.998704
2       13  Walking  0.221782  0.375365  1.277480
3       25  Walking  0.167558  0.386942  1.495453
4       11  Walking  0.330682  0.558338  1.472442

In [4]:
# iloc selects by integer position.
# This means: first 5 rows and first 4 columns.
df.iloc[:5, :4]

   row_id  subject  time_step activity
0       1        3          0  Walking
1       2       24          1  Walking
2       3       13          2  Walking
3       4       25          3  Walking
4       5       11          4  Walking

In [5]:
# loc selects by labels.
# This means: rows 0 through 4 and these named columns.
df.loc[0:4, ["row_id", "subject", "activity", "device"]]

   row_id  subject activity   device
0       1        3  Walking  phone_A
1       2       24  Walking  phone_B
2       3       13  Walking  phone_A
3       4       25  Walking  phone_A
4       5       11  Walking  phone_A

## Summary
Use column names when meaning matters.

Use `iloc` when position matters.