# 14 — Filter Activity Rows

## Goal
To use conditions to keep only the rows needed for a specific question.

In [1]:
from pathlib import Path

import numpy as np
import pandas as pd

DATA_DIR = Path("../data")
RAW_PATH = DATA_DIR / "raw" / "motionsense_raw.csv"
PROCESSED_DIR = DATA_DIR / "processed"

pd.set_option("display.max_columns", 20)
pd.set_option("display.width", 120)

## Filtering
Filtering selects rows that match a condition.

Common examples:
- keep only Walking rows
- keep one device
- keep selected activities

In [2]:
df = pd.read_csv(RAW_PATH)

# Keep only Walking rows.
walking_df = df[df["activity"] == "Walking"]

print("Original shape:", df.shape)
print("Walking shape:", walking_df.shape)
walking_df.head()

Original shape: (1320, 11)
Walking shape: (220, 11)

   row_id  subject  time_step activity     acc_x     acc_y     acc_z    gyro_x    gyro_y    gyro_z   device
0       1        3          0  Walking -0.190664  0.687583  1.129328  0.005386 -0.143240  0.014062  phone_A
1       2       24          1  Walking  0.010593  0.542629  0.998704  0.316734  0.085557  0.007263  phone_B
2       3       13          2  Walking  0.221782  0.375365  1.277480  0.114523  0.096630 -0.005492  phone_A
3       4       25          3  Walking  0.167558  0.386942  1.495453  0.203002 -0.047116 -0.038735  phone_A
4       5       11          4  Walking  0.330682  0.558338  1.472442  0.455581 -0.044706 -0.056347  phone_A

In [3]:
# Keep rows where the device is phone_A.
phone_a_df = df[df["device"] == "phone_A"]

print("phone_A rows:", phone_a_df.shape[0])
phone_a_df.head()

phone_A rows: 635

   row_id  subject  time_step activity     acc_x     acc_y     acc_z    gyro_x    gyro_y    gyro_z   device
0       1        3          0  Walking -0.190664  0.687583  1.129328  0.005386 -0.143240  0.014062  phone_A
2       3       13          2  Walking  0.221782  0.375365  1.277480  0.114523  0.096630 -0.005492  phone_A
3       4       25          3  Walking  0.167558  0.386942  1.495453  0.203002 -0.047116 -0.038735  phone_A
4       5       11          4  Walking  0.330682  0.558338  1.472442  0.455581 -0.044706 -0.056347  phone_A
5       6       15          5  Walking  0.172612  0.558959  1.635700  0.207466 -0.092417 -0.090693  phone_A

In [4]:
# isin() keeps rows where the value is in a list.
selected_activities = ["Walking", "Standing"]
selected_df = df[df["activity"].isin(selected_activities)]

print(selected_df["activity"].value_counts())
selected_df.head()

activity
Walking     220
Standing    220
Name: count, dtype: int64

   row_id  subject  time_step activity     acc_x     acc_y     acc_z    gyro_x    gyro_y    gyro_z   device
0       1        3          0  Walking -0.190664  0.687583  1.129328  0.005386 -0.143240  0.014062  phone_A
1       2       24          1  Walking  0.010593  0.542629  0.998704  0.316734  0.085557  0.007263  phone_B
2       3       13          2  Walking  0.221782  0.375365  1.277480  0.114523  0.096630 -0.005492  phone_A
3       4       25          3  Walking  0.167558  0.386942  1.495453  0.203002 -0.047116 -0.038735  phone_A
4       5       11          4  Walking  0.330682  0.558338  1.472442  0.455581 -0.044706 -0.056347  phone_A

## Summary
Filtering turns a large dataset into a focused dataset for one research question.