# 07 — Filtering and Sorting Activity Data

**Goal:** To keep only rows that match a condition.

In [1]:
from pathlib import Path
import numpy as np
import pandas as pd

DATA_PATH = Path('../data/raw/motionsense_raw.csv')

df = pd.read_csv(DATA_PATH)
df.head()

,row_id,subject,time_step,activity,acc_x,acc_y,acc_z,gyro_x,gyro_y,gyro_z,device
0,1,3,0,Walking,-0.190664,0.687583,1.129328,0.005386,-0.143240,0.014062,phone_A
1,2,24,1,Walking,0.010593,0.542629,0.998704,0.316734,0.085557,0.007263,phone_B
2,3,13,2,Walking,0.221782,0.375365,1.277480,0.114523,0.096630,-0.005492,phone_A
3,4,25,3,Walking,0.167558,0.386942,1.495453,0.203002,-0.047116,-0.038735,phone_A
4,5,11,4,Walking,0.330682,0.558338,1.472442,0.455581,-0.044706,-0.056347,phone_A

In [2]:
# Count how many rows belong to each activity.
# This helps us understand the target column.
df['activity'].value_counts()

activity
Walking               220
Walking Upstairs      220
Walking Downstairs    220
Sitting               220
Standing              220
Laying                220
Name: count, dtype: int64

In [3]:
# Keep only Walking rows.
walking_df = df[df['activity'] == 'Walking']

print('Walking rows:', walking_df.shape[0])
walking_df.head()

Walking rows: 220

,row_id,subject,time_step,activity,acc_x,acc_y,acc_z,gyro_x,gyro_y,gyro_z,device
0,1,3,0,Walking,-0.190664,0.687583,1.129328,0.005386,-0.143240,0.014062,phone_A
1,2,24,1,Walking,0.010593,0.542629,0.998704,0.316734,0.085557,0.007263,phone_B
2,3,13,2,Walking,0.221782,0.375365,1.277480,0.114523,0.096630,-0.005492,phone_A
3,4,25,3,Walking,0.167558,0.386942,1.495453,0.203002,-0.047116,-0.038735,phone_A
4,5,11,4,Walking,0.330682,0.558338,1.472442,0.455581,-0.044706,-0.056347,phone_A

In [7]:
# Keep only rows where acc_z is greater than 1.2.
# This is a simple numerical filter.
high_acc_z = df[df['acc_z'] > 1.2]

print('Rows with high acc_z:', high_acc_z.shape[0])
high_acc_z.head()

Rows with high acc_z: 274

,row_id,subject,time_step,activity,acc_x,acc_y,acc_z,gyro_x,gyro_y,gyro_z,device
2,3,13,2,Walking,0.221782,0.375365,1.277480,0.114523,0.096630,-0.005492,phone_A
3,4,25,3,Walking,0.167558,0.386942,1.495453,0.203002,-0.047116,-0.038735,phone_A
4,5,11,4,Walking,0.330682,0.558338,1.472442,0.455581,-0.044706,-0.056347,phone_A
5,6,15,5,Walking,0.172612,0.558959,1.635700,0.207466,-0.092417,-0.090693,phone_A
6,7,17,6,Walking,0.511165,0.502007,1.434606,0.245538,0.012835,0.024056,phone_A

In [5]:
# Sort rows by acc_z from highest to lowest.
# This helps us quickly see the largest values.
sorted_df = df.sort_values(by='acc_z', ascending=False)
sorted_df.head()

,row_id,subject,time_step,activity,acc_x,acc_y,acc_z,gyro_x,gyro_y,gyro_z,device
316,317,23,96,Walking Upstairs,-0.736950,0.959533,2.337039,0.307639,0.075804,-0.064072,phone_A
256,257,5,36,Walking Upstairs,-1.048509,-0.191113,2.114495,0.414881,-0.090508,0.029116,phone_A
343,344,27,123,Walking Upstairs,0.294179,-0.586548,2.084589,0.296048,0.063061,-0.140083,phone_A
408,409,10,188,Walking Upstairs,-0.912049,0.027427,2.073034,0.122540,-0.246716,0.167257,phone_B
289,290,17,69,Walking Upstairs,0.084034,-0.353800,2.027561,0.445293,-0.211391,0.094231,phone_A

## Summary

Filtering answers questions like:

- Show only Walking rows.
- Show rows with high acceleration.
- Sort values to find largest or smallest readings.